```{r}
library(Seurat)
library(dplyr)
library(viridis)
library(ggplot2)
library(Matrix)
library(RColorBrewer)
library(scales)
library(data.table)
```

###### Preprocessing Steps

# Load the dataset and create a Seurat Object
```{r}
WT_dir <- '/Users/jamrute/Documents/Graduate_School/Thesis_Lab/Lavine_Projects/Secondary/Ben_transplant/MyD88_KO/Matrices/Wildtype-WT/filtered_feature_bc_matrix/'
WT.data <- Read10X(data.dir =WT_dir)
WT <- CreateSeuratObject(counts = WT.data, min.cells = 3, min.features = 200)
WT$condition <- "WT"

MyD88KO_dir <- '/Users/jamrute/Documents/Graduate_School/Thesis_Lab/Lavine_Projects/Secondary/Ben_transplant/MyD88_KO/Matrices/MyD88_Day_3KO/filtered_feature_bc_matrix/'
MyD88KO.data <- Read10X(data.dir =MyD88KO_dir)
MyD88KO <- CreateSeuratObject(counts = MyD88KO.data, min.cells = 3, min.features = 200)
MyD88KO$condition <- "MyD88KO"

sample <- merge(WT, y = c(MyD88KO))
```

# Look at the features
```{r}
sample[["percent.mt"]] <- PercentageFeatureSet(sample, pattern = "^mt-")
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "orig.ident")
```

# Filtering
```{r}
sample <- subset(sample, subset = nFeature_RNA < 6000 & nCount_RNA < 50000 & percent.mt < 10)
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "condition")
```

```{r}
save(sample,file="./merged_postQC.Robj")
```

```{r}
DefaultAssay(sample) <- 'RNA'
sample <- SCTransform(sample, vars.to.regress = c("percent.mt"))
```

```{r}
sample <- RunPCA(sample, features = VariableFeatures(object = sample), npcs=100, verbose=TRUE)
```

```{r}
ElbowPlot(sample, ndims=100, reduction = "pca")
```

```{r}
sample <- FindNeighbors(sample, dims = 1:50, verbose = FALSE)
sample <- FindClusters(sample, resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8), verbose = FALSE)
sample <- RunUMAP(sample, dims = 1:50, verbose = FALSE)
```

```{r}
DimPlot(sample, group.by = "SCT_snn_res.0.4")
```

```{r}
DimPlot(sample, group.by = "SCT_snn_res.0.4", split.by = "condition")
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "SCT_snn_res.0.4"
sample.rnamarkers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.rnamarkers, file ="./DE_res0.4.csv", quote = FALSE)
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "condition"
sample.rnamarkers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.rnamarkers, file ="./DE_condition.csv", quote = FALSE)
```

```{r}
saveRDS(sample, "./combined_processed.rds")
```

```{r}
sample <- readRDS("./pre-cleaning/combined_processed.rds")
```

```{r}
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "condition")
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "SCT_snn_res.0.4")
```
# Clean Up

```{r}
Idents(sample) <- "SCT_snn_res.0.4"
levels(sample)
```

```{r}
sample <- subset(sample, idents = c("0","1","2","3","5","7","9"))
```

```{r}
DefaultAssay(sample) <- 'RNA'
sample <- SCTransform(sample, vars.to.regress = c("percent.mt"))
```

```{r}
sample <- RunPCA(sample, features = VariableFeatures(object = sample), npcs=100, verbose=FALSE)
```

```{r}
ElbowPlot(sample, ndims=100, reduction = "pca")
```

```{r}
sample <- FindNeighbors(sample, dims = 1:50, verbose = FALSE)
sample <- FindClusters(sample, resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8), verbose = FALSE)
sample <- RunUMAP(sample, dims = 1:50, verbose = FALSE)
```

```{r}
DimPlot(sample, group.by = "SCT_snn_res.0.4")
```

```{r}
DimPlot(sample, group.by = "SCT_snn_res.0.4", split.by = "condition")
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "SCT_snn_res.0.4"
sample.rnamarkers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.rnamarkers, file ="./post-cleaning/DE_res0.4.csv", quote = FALSE)
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "condition"
sample.rnamarkers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.rnamarkers, file ="./post-cleaning/DE_condition.csv", quote = FALSE)
```

```{r}
saveRDS(sample, "./post-cleaning/cleaned.rds")
```

```{r}
sample <- readRDS("./post-cleaning/cleaned.rds")
```

```{r}
unique(sample$SCT_snn_res.0.4)
```

```{r}
fun <- function(x) {
  if (x == "0") {"Monocyte"} 
  else if (x == "1") {"MHC II High"}
  else if (x == "2") {"Arg1"}
  else if (x == "3") {"Ccl8"}
  else if (x == "4") {"Prolif"}
  else if (x == "5") {"IFN"}
  else if (x == "6") {"Resident Mac"}
  else if (x == "7") {"Neutrophils"}

}

# Filter for only Donor and Day 0
sample$annotations <- mapply(fun, sample$SCT_snn_res.0.4)
```

```{r}
DimPlot(sample, group.by = "annotations", split.by = "condition")
```

```{r}
FeaturePlot(sample, features = "Lyve1")
```

```{r}
ggplot(sample@meta.data, aes(x=condition, fill=annotations)) + geom_bar(position = "fill") + theme_bw() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "annotations"
sample.rnamarkers <- FindAllMarkers(sample, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.rnamarkers, file ="./annotation/DE_annotations.csv", quote = FALSE)
```

```{r}
DefaultAssay(sample) <- 'SCT'
Idents(sample) <- "annotations"
DotPlot(sample, features = c("Ly6c2", "Ifit1", "Arg1", "Mki67", "Ccl8", "H2-Aa", "Lyve1", "Retnlg"), cols = c("lightgrey", "blue"), col.min = 0) + RotatedAxis()

```


```{r}
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "condition")
VlnPlot(sample, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "annotations")
```

```{r}
sample$annotations <- factor(sample$annotations, levels = c("Monocyte", "IFN", "Arg1", "Prolif", "Ccl8", "MHC II High", "Resident Mac", "Neutrophils"), ordered = TRUE)
```

```{r}
VlnPlot(sample, features = c("Ly6c2", "Ifit1", "Arg1", "Mki67", "Ccl8", "H2-Aa", "Lyve1", "Retnlg"), stack = TRUE, group.by = "annotations") + NoLegend()
```



