```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
```

```{r}
sample.integrated <- readRDS("./pre_cleanUp/donor_integrated.rds")
```

```{r}
DimPlot(sample.integrated, reduction = "umap", group.by = "integrated_snn_res.0.3", repel = TRUE)
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "integrated_snn_res.0.3", repel = TRUE)
```

```{r}
Idents(sample.integrated) <- "integrated_snn_res.0.3"
sample.integrated_A <- FindSubCluster(sample.integrated, cluster = "3", algorithm = 3, resolution = 0.9, graph.name = "integrated_snn")
Idents(sample.integrated_A) <- "sub.cluster"
```

```{r}
DimPlot(sample.integrated_A, reduction = "umap", group.by = "sub.cluster", repel = TRUE, label = TRUE)
DimPlot(sample.integrated_A, reduction = "umap", split.by = "orig.ident", group.by = "sub.cluster", repel = TRUE)
```

```{r}
DefaultAssay(sample.integrated_A) <- 'RNA'
sample.integrated_A <- NormalizeData(sample.integrated_A)
```

```{r}
Idents(sample.integrated_A) <- "sub.cluster"
DefaultAssay(sample.integrated_A) <- 'RNA'
sample.integrated_A.markers <- FindAllMarkers(sample.integrated_A, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.integrated_A.markers, file ="/Users/jamrute/Desktop/integrated_snn_res.0.3_subcluster_DGE.csv", quote = FALSE)
```


```{r}
FeaturePlot(sample.integrated_A, features = c("Neat1", "Malat1"))
VlnPlot(sample.integrated_A, features = c("Neat1", "Malat1"), stack=TRUE, group.by = "sub.cluster")
VlnPlot(sample.integrated_A, features = c("nCount_RNA", "percent.mt"), stack=TRUE, group.by = "sub.cluster")
```

```{r}
Idents(sample.integrated_A) <- "sub.cluster"
donor_filtered <- subset(sample.integrated_A, idents = c("0","1","2","3_0","3_1","3_2","3_3","3_4","5","6","7"))
```

```{r}
DimPlot(donor_filtered, reduction = "umap", group.by = "sub.cluster", repel = TRUE, label = TRUE)
DimPlot(donor_filtered, reduction = "umap", split.by = "orig.ident", group.by = "sub.cluster", repel = TRUE)
```
```{r}
DefaultAssay(donor_filtered) <- 'RNA'
Idents(donor_filtered) <- "sub.cluster"
donor_filtered.rnamarkers <- FindAllMarkers(donor_filtered, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(donor_filtered.rnamarkers, file ="/Users/jamrute/Desktop/res03_sub.cluster_DE.csv", quote = FALSE)
```

```{r}
fun <- function(x) {
  if (x == "0") {"Resident Macs"} 
  else if (x == "1") {"Cd74/MHC II High"}
  else if (x == "2") {"Cxcl2/Ccl7"}
  else if (x == "3_0") {"Cd209a"}
  else if (x == "3_1") {"Arg1"}
  else if (x == "3_2") {"Ly6c2 Mono"}
  else if (x == "3_3") {"Ly6c2 Mono"}
  else if (x == "3_4") {"NC Mono"}
  else if (x == "5") {"Cd207/Vsig4"}
  else if (x == "6") {"Prolif"}
  else if (x == "7") {"IFN"}
}

# Filter for only Donor and Day 0
donor_filtered$annotations <- mapply(fun, donor_filtered$sub.cluster)
```

```{r}
DimPlot(donor_filtered, reduction = "umap", split.by = "orig.ident", group.by = "annotations", repel = TRUE)
DimPlot(donor_filtered, reduction = "umap", group.by = "annotations", repel = TRUE)
```
```{r}
FeaturePlot(donor_filtered, features = c("Ccr2"))
FeaturePlot(donor_filtered, split.by = "orig.ident",features = c("Ccr2"))

VlnPlot(donor_filtered, features = c("Ccr2"), group.by = "annotations")
VlnPlot(donor_filtered, split.by = "orig.ident",features = c("Ccr2"), group.by = "annotations")
```

```{r}
donor_filtered$CCR2 <- ifelse(donor_filtered$annotations %in% c("Cd209a", "Ly6c2 Mono"), "CCR2+", "CCR2-") 
donor_filtered$opStatus <- ifelse(donor_filtered$orig.ident == "BD", "Pre-Op", "Post-Op") 
```

```{r}
DimPlot(donor_filtered, reduction = "umap", group.by = "CCR2", repel = TRUE)
```

```{r}
saveRDS(donor_filtered, "./post_cleanUp/annotated/donor_integrated_annotated.rds")
```















