```{r}
library(clusterProfiler)
library(DOSE)
library(enrichplot)
library(ReactomePA)
library(ggplot2)
library(dplyr)
```

```{r}
d <- read.csv("./figure3_panels/CCR2-/CCR2Negative_Pre_vs_Post_Op_DGE.csv")
d <- filter(d, d$p_val < 0.05)
d <- filter(d, d$cluster == "Post-Op")
d
```

```{r}
eg <- bitr(as.character(d$gene), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
```

```{r}
d <- filter(d, gene %in% eg$SYMBOL)
d$gene <- eg$ENTREZID
## feature 1: numeric vector
geneList = d[,3]
## feature 2: named vector
names(geneList) = as.character(d[,8])
## feature 3: decreasing order
geneList = sort(geneList, decreasing = TRUE)
```

###  WikiPathways

# ORA UP
```{r}
gene <- names(geneList)[geneList > 0]
pathways <- enrichWP(gene, organism = "Mus musculus")
dotplot(pathways) + scale_color_gradientn(colors=c("red","lightgrey", "blue"), oob=scales::squish) + theme(axis.text.x = element_text(size = 5, angle = 0, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(size = 10, angle = 0, hjust = 1, vjust = 0, face = "plain"), axis.title.x=element_blank())
```

```{r}
## convert gene ID to Symbol
edox <- setReadable(pathways, 'org.Mm.eg.db', 'ENTREZID')
```

```{r}
cnetplot(edox, foldChange=geneList, circular = TRUE, colorEdge = TRUE, node_label = "none") + scale_color_gradientn(colors=c("red","lightgrey", "blue"), oob=scales::squish)
```

```{r}
cnetplot(edox, node_label="all")
```









