```{r}
library(Seurat)
library(dplyr)
library(viridis)
library(ggplot2)
library(Matrix)
library(RColorBrewer)
library(scales)
library(data.table)
library(pheatmap)
library(Seurat)
library(ggplot2)
library(patchwork)
library(ggpubr)
library(dplyr)
library(Seurat)
library(patchwork)
library(sctransform)
library(ggplot2)
library(pheatmap)
library(Seurat)
library(ggplot2)
library(Matrix)
library(RColorBrewer)
library(dplyr)
library(scales)
library(data.table)
library(stats)
library("Nebulosa")
```

```{r}
donor_integrated <- readRDS("./post_cleanUp/annotated/donor_integrated_annotated.rds")
```

```{r}
DefaultAssay(donor_integrated) <- 'RNA'
donor_integrated <- NormalizeData(donor_integrated)
all.genes <- rownames(donor_integrated)
donor_integrated <- ScaleData(donor_integrated, features = all.genes)
```

```{r}
donor_integrated$orig.ident <- factor(donor_integrated$orig.ident, levels = c("BD", "Pod1D", "Pod7D"), ordered = TRUE)
#donor_integrated$annotations <- factor(donor_integrated$annotations, levels = c(""), ordered = TRUE)
```

```{r}
DimPlot(donor_integrated, reduction = "umap", split.by = "orig.ident", group.by = "annotations", repel = TRUE)
```

```{r}
Idents(donor_integrated) <- "orig.ident"
BD <- subset(donor_integrated, idents = "BD")
Pod1D <- subset(donor_integrated, idents = "Pod1D")
Pod7D <- subset(donor_integrated, idents = "Pod7D")
DimPlot(donor_integrated, reduction = "umap", split.by = "orig.ident", group.by = "annotations", repel = TRUE)
DimPlot(BD, reduction = "umap", group.by = "annotations", repel = TRUE)
DimPlot(Pod1D, reduction = "umap", group.by = "annotations", repel = TRUE)
DimPlot(Pod7D, reduction = "umap", group.by = "annotations", repel = TRUE)
```

```{r}
DimPlot(donor_integrated, reduction = "umap", group.by = "annotations", repel = TRUE)
DimPlot(donor_integrated, reduction = "umap", group.by = "annotations", repel = TRUE, label=TRUE) + NoLegend()
```

# Look at cell type breakdown
```{r}
ggplot(donor_integrated@meta.data, aes(x=orig.ident, fill=annotations)) + geom_bar(position = "fill") + theme_bw() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
DimPlot(donor_integrated, reduction = "umap", group.by = "GFP", repel = TRUE, cols=c("gray75", "green3"))
```

# Perform a DGE for all the cell types
```{r}
DefaultAssay(donor_integrated) <- 'RNA'
Idents(donor_integrated) <- "annotations"
donor_integrated.rnamarkers <- FindAllMarkers(donor_integrated, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(donor_integrated.rnamarkers, file ="/Users/jamrute/Desktop/annotations_DGE.csv", quote = FALSE)
donor_integrated.rnamarkers
```

```{r}
top2 <- donor_integrated.rnamarkers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)
top2
```

```{r}
DefaultAssay(donor_integrated) <- 'RNA'
Idents(donor_integrated) <- "annotations"
DotPlot(donor_integrated, features = c("Cd74", "Folr2", "Ly6c2", "Cxcl2", "Cd207", "Cd209a", "Ifit3", "Mki67", "Arg1", "Ace")) + RotatedAxis()
```

```{r}
DefaultAssay(donor_integrated) <- 'RNA'
Idents(donor_integrated) <- "annotations"
DotPlot(donor_integrated, features = c("Ccr2", "C1qa", "C1qc","Folr2", "Cd163", "H2-Aa", "Ly6c2", "Plac8")) + RotatedAxis()
```

```{r}
unique(donor_integrated$annotations)
```

```{r}
DefaultAssay(donor_integrated) <- 'RNA'
donor_integrated$annotations <- factor(donor_integrated$annotations, levels = c("Resident Macs", "Cxcl2/Ccl7", "IFN", "Cd207/Vsig4", "Prolif", "Arg1", "Cd74/MHC II High", "Cd209a", "Ly6c2 Mono", "NC Mono"), ordered = TRUE)

DotPlot(donor_integrated, features = c("C1qa", "H2-Aa", "Ccr2", "Folr2", "Cxcl2", "Ifit3", "Cd207", "Mki67", "Arg1", "Cd74", "Cd209a", "Ly6c2", "Ace"), group.by = "annotations") + RotatedAxis() + 
```

```{r}
top10 <- donor_integrated.rnamarkers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
unique(top10$cluster)
```

```{r}
expdata <- GetAssayData(donor_integrated)
#Pop1<-filter(top10, cluster == "NC Mono")$gene
Pop1 <- c("Plac8","Ly6c2","Ccr2","Napsa","Gm9733","Itgb7","Mcemp1","Ltb4r1","Hp","Cytip")
pops<-list(Pop1)

#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
donor_integrated@meta.data$pop1_z<-z_scores[1,]
FeaturePlot(object=donor_integrated, features = "pop1_z",pt.size=.5) + scale_color_gradientn(colors=c("blue","turquoise2","yellow","red","red4"), oob=scales::squish, limits=c(0,0.5))
```

```{r}
DefaultAssay(donor_integrated) <- 'RNA'
Idents(donor_integrated) <- "CCR2"
donor_integrated.rnamarkers <- FindAllMarkers(donor_integrated, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
#write.csv(donor_integrated.rnamarkers, file ="/Users/jamrute/Desktop/CCR2_pos_vs_neg_DGE.csv", quote = FALSE)
donor_integrated.rnamarkers
```

```{r}
top10 <- donor_integrated.rnamarkers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DotPlot(donor_integrated, features = top10$gene) + RotatedAxis()
```

```{r}
DefaultAssay(donor_integrated) <- 'SCT'
top10 <- donor_integrated.rnamarkers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(donor_integrated, features = top10$gene, group.by = "CCR2") + NoLegend() + scale_fill_viridis()
```

```{r}
# CCR2+ DGE
Idents(donor_integrated) <- "CCR2"
donor_integrated.ccr2Pos <- subset(donor_integrated, idents = c("CCR2+"))

DefaultAssay(donor_integrated.ccr2Pos) <- 'RNA'
Idents(donor_integrated.ccr2Pos) <- "opStatus"
donor_integrated.ccr2Pos.markers <- FindAllMarkers(donor_integrated.ccr2Pos, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.01)
write.csv(donor_integrated.ccr2Pos.markers, file ="/Users/jamrute/Desktop/CCR2Positive_Pre_vs_Post_Op_DGE_SCT.csv", quote = FALSE)
```

```{r}
top10 <- donor_integrated.ccr2Pos.markers %>% group_by(cluster) %>% top_n(n = 100, wt = avg_log2FC)
DoHeatmap(donor_integrated.ccr2Pos, features = top10$gene, group.by = "opStatus") + NoLegend() + scale_fill_viridis() + 
    theme(text = element_text(size = 2))

DoHeatmap(donor_integrated.ccr2Pos, features = top10$gene, group.by = "orig.ident") + NoLegend() + scale_fill_viridis() + 
    theme(text = element_text(size = 2))
```

```{r}
# CCR2- DGE
Idents(donor_integrated) <- "CCR2"
donor_integrated.ccr2Neg <- subset(donor_integrated, idents = c("CCR2-"))

DefaultAssay(donor_integrated.ccr2Neg) <- 'RNA'
Idents(donor_integrated.ccr2Neg) <- "opStatus"
donor_integrated.ccr2Neg.markers <- FindAllMarkers(donor_integrated.ccr2Neg, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.01)
write.csv(donor_integrated.ccr2Neg.markers, file ="/Users/jamrute/Desktop/CCR2Negative_Pre_vs_Post_Op_DGE_SCT.csv", quote = FALSE)
```

```{r}
top10 <- donor_integrated.ccr2Neg.markers %>% group_by(cluster) %>% top_n(n = 100, wt = avg_log2FC)
DoHeatmap(donor_integrated.ccr2Neg, features = top10$gene, group.by = "opStatus", ) + NoLegend() + scale_fill_viridis() + 
    theme(text = element_text(size = 2))

DoHeatmap(donor_integrated.ccr2Neg, features = top10$gene, group.by = "orig.ident") + NoLegend() + scale_fill_viridis() + 
    theme(text = element_text(size = 2))
```

# Look at Marker Genes
```{r}
DefaultAssay(donor_integrated) <- "RNA"
FeaturePlot(object=donor_integrated, features = "Ccr2", split.by = "orig.ident")
```
# CCR2+ : NF-kB
```{r}
DefaultAssay(donor_integrated) <- 'RNA'
NF_kB <- list(c("Cxcl3", "Saa3", "Cxcl1", "Arg1", "Ccl17", "Lrg1", "Ccrl2", "G0s2", "Cxcl2", "Ccl9", "Hif1a", "Irg1", "Ccl6", "Trem1", "Il1r2", "Itgam", "Il1a", "Vegfa", "Cd14", "Il1rn", "Nfkb1"))

donor_integrated <- AddModuleScore(
  object = donor_integrated,
  features = NF_kB,
  name = 'NF_kB'
)
```

# CCR2- : IFN-g
```{r}
DefaultAssay(donor_integrated) <- 'RNA'
IFN_g <- list(c("Cxcl9", "Ly6a", "Ccl8", "Ccl5", "Cxcl10", "Fcgr4", "Ifi30", "Stat1"))

donor_integrated <- AddModuleScore(
  object = donor_integrated,
  features = IFN_g,
  name = 'IFN_g'
)
```


```{r}
write.csv(donor_integrated@meta.data, file = "./genesets_meta.csv", quote = FALSE)
```









