```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
options(future.globals.maxSize = 8000 * 1024^2)
```

```{r}
load('../filtered_transplant_updated.Robj')
```

```{r}
sample <- ben_transplant_updated
```

```{r}
sample.list <- SplitObject(sample, split.by = "orig.ident")
sample.list <- sample.list[c("BD","Pod1D","Pod7D")]
sample.list <- lapply(X = sample.list, FUN = SCTransform)
```

```{r}
sample.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 3000)
sample.list <- PrepSCTIntegration(object.list = sample.list, anchor.features = sample.features, 
    verbose = FALSE)

sample.anchors <- FindIntegrationAnchors(object.list = sample.list, normalization.method = "SCT", 
    anchor.features = sample.features, verbose = FALSE)
sample.integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", 
    verbose = FALSE)

sample.integrated <- RunPCA(sample.integrated, features = VariableFeatures(object = sample.integrated), npcs=50, verbose=TRUE)
sample.integrated <- FindNeighbors(sample.integrated, dims = 1:50, verbose = FALSE)
sample.integrated <- FindClusters(sample.integrated, resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0), verbose = FALSE)
sample.integrated <- RunUMAP(sample.integrated, dims = 1:50, verbose = FALSE)
```

```{r}
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "integrated_snn_res.0.3", repel = TRUE)
```

```{r}
saveRDS(sample.integrated, "./donor_integrated.rds")
```

```{r}
DimPlot(sample.integrated, reduction = "umap", group.by = "integrated_snn_res.2", repel = TRUE, label=TRUE)
FeaturePlot(sample.integrated, features = c("Ccr2"))

DimPlot(sample.integrated, split.by = "orig.ident",reduction = "umap", group.by = "integrated_snn_res.2", repel = TRUE, label=TRUE)
FeaturePlot(sample.integrated, split.by = "orig.ident",features = c("Ccr2"))

VlnPlot(sample.integrated, features = c("Ccr2"), group.by = "integrated_snn_res.2")
VlnPlot(sample.integrated, split.by = "orig.ident",features = c("Ccr2"), group.by = "integrated_snn_res.2")
```

```{r}
sample.integrated$CCR2 <- ifelse(sample.integrated$integrated_snn_res.2 %in% c("12", "16"), "CCR2+", "CCR2-") 
sample.integrated$opStatus <- ifelse(sample.integrated$orig.ident == "BD", "Pre-Op", "Post-Op") 
```

```{r}
sample.integrated <- readRDS("./donor_integrated.rds")
```

```{r}
DefaultAssay(sample.integrated) <- 'RNA'
sample.integrated <- NormalizeData(sample.integrated)
```

```{r}
# CCR2+ DGE
Idents(sample.integrated) <- "CCR2"
sample.integrated.ccr2Pos <- subset(sample.integrated, idents = c("CCR2+"))

DefaultAssay(sample.integrated.ccr2Pos) <- 'RNA'
Idents(sample.integrated.ccr2Pos) <- "opStatus"
sample.integrated.ccr2Pos.markers <- FindAllMarkers(sample.integrated.ccr2Pos, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.01)
write.csv(sample.integrated.ccr2Pos.markers, file ="./TRIAL_CCR2Positive_Pre_vs_Post_Op_DGE_SCT.csv", quote = FALSE)
```

```{r}
# CCR2+ DGE
Idents(sample.integrated) <- "CCR2"
sample.integrated.ccr2Pos <- subset(sample.integrated, idents = c("CCR2-"))

DefaultAssay(sample.integrated.ccr2Pos) <- 'SCT'
Idents(sample.integrated.ccr2Pos) <- "opStatus"
sample.integrated.ccr2Pos.markers <- FindAllMarkers(sample.integrated.ccr2Pos, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.01)
write.csv(sample.integrated.ccr2Pos.markers, file ="./TRIAL_CCR2Positive_Pre_vs_Post_Op_DGE_SCT.csv", quote = FALSE)
```














