```{r}
library(Seurat)
library(dplyr)
library(viridis)
library(ggplot2)
library(Matrix)
library(RColorBrewer)
library(scales)
library(data.table)
```

```{r}
recipient_integrated <- readRDS("./Integration/post_cleanup/recipient_integrated_annotated.rds")
```

```{r}
recipient_integrated$orig.ident <- factor(recipient_integrated$orig.ident, levels = c("Pod1R", "Pod7R", "Pod14R"), ordered = TRUE)
```

```{r}
Idents(recipient_integrated) <- "orig.ident"
Pod1R <- subset(recipient_integrated, idents = "Pod1R")
Pod7R <- subset(recipient_integrated, idents = "Pod7R")
Pod14R <- subset(recipient_integrated, idents = "Pod14R")
DimPlot(recipient_integrated, reduction = "umap", split.by = "orig.ident", group.by = "annotations", repel = TRUE)
DimPlot(Pod1R, reduction = "umap", group.by = "annotations", repel = TRUE)
DimPlot(Pod7R, reduction = "umap", group.by = "annotations", repel = TRUE)
DimPlot(Pod14R, reduction = "umap", group.by = "annotations", repel = TRUE)
```

```{r}
DimPlot(recipient_integrated, reduction = "umap", group.by = "annotations", repel = TRUE, ncol=3)
```

# Look at cell type breakdown
```{r}
ggplot(recipient_integrated@meta.data, aes(x=annotations, fill=orig.ident)) + geom_bar(position = "fill") + theme_bw() + scale_fill_manual(values=c("rosybrown", "red", "red4")) + theme(axis.text.x = element_text(angle = 90))
ggplot(recipient_integrated@meta.data, aes(x=orig.ident, fill=annotations)) + geom_bar(position = "fill") + theme_bw() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
DefaultAssay(recipient_integrated) <- 'RNA'
recipient_integrated <- NormalizeData(recipient_integrated)
```

# Perform a DGE for all the cell types
```{r}
DefaultAssay(recipient_integrated) <- 'RNA'
Idents(recipient_integrated) <- "annotations"
recipient_integrated.rnamarkers <- FindAllMarkers(recipient_integrated, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(recipient_integrated.rnamarkers, file ="./Integration/annotations_DGE.csv", quote = FALSE)
recipient_integrated.rnamarkers
```

```{r}
recipient_integrated.rnamarkers <- read.csv2('./figure2_recipient_panels/annotations_DGE.csv', header=TRUE, sep=',', row.names = 1)
recipient_integrated.rnamarkers
```

```{r}
top10 <- recipient_integrated.rnamarkers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
unique(top10$cluster)
```


```{r}
expdata <- GetAssayData(recipient_integrated)
Pop1<-filter(top10, cluster == "NC Mono")$gene
#Pop1 <- c()
pops<-list(Pop1)

#Z-Scores
z_scores<-NULL

for (i in 1:length(pops)) {
genes <- pops[[i]]
zz <- which(tolower(rownames(expdata)) %in% tolower(genes))
av <- numeric(ncol(expdata))

geneExp <- as.matrix(expdata[zz, ])
geneExp <- t(scale(t(geneExp)))
geneExp[is.nan(geneExp)] <- 0
z_scores <- rbind(z_scores,(av + colSums(geneExp) / length(zz)))
}
recipient_integrated@meta.data$pop1_z<-z_scores[1,]
FeaturePlot(object=recipient_integrated, features = "pop1_z",pt.size=.5, ncol=3) + scale_color_gradientn(colors=c("blue","turquoise2","yellow","red","red4"), oob=scales::squish, limits=c(0,2))
```

```{r}
DefaultAssay(recipient_integrated) <- 'RNA'
Idents(recipient_integrated) <- "annotations"
#VlnPlot(recipient_integrated, features = c("Ccr7", "Ccl8", "Ube2c", "Cxcl2", "Plac8", "Arg1", "ACE"), stack = TRUE)
DotPlot(recipient_integrated, features = c("Cd209a", "Ccl8", "Mki67", "Cxcl2", "Ly6c2", "Arg1", "Ace")) + RotatedAxis()
```

###### Overlaying Palantir results on UMAP

```{r}
Myeloid_1 <- recipient_integrated
```

```{r}
meta <- read.csv2('./Integration/palantir/sct_CC_regressed/myeloid_palantir_meta_data.csv', header=TRUE, sep=',', row.names = 1)
Myeloid_2 <- AddMetaData(Myeloid_1, meta)

Myeloid_2@meta.data$pseudotime <- as.numeric(as.character(Myeloid_2@meta.data$pseudotime))
Myeloid_2@meta.data$entropy <- as.numeric(as.character(Myeloid_2@meta.data$entropy))
```

```{r}
Myeloid_2$orig.ident <- factor(Myeloid_2$orig.ident, levels = c("Pod1R", "Pod7R", "Pod14R"), ordered = TRUE)
```

```{r}
FeaturePlot(Myeloid_2, reduction = "umap", features = c("pseudotime")) + scale_color_viridis()
FeaturePlot(Myeloid_2, reduction = "umap", features = c("entropy"))  + scale_color_viridis()
DimPlot(Myeloid_2, group.by = "annotations")
```

```{r}
FeaturePlot(Myeloid_2, reduction = "umap", features = c("pseudotime"), split.by = "orig.ident", cols = viridis(10))
FeaturePlot(Myeloid_2, reduction = "umap", features = c("entropy"), split.by = "orig.ident", cols = viridis(256))

DimPlot(Myeloid_2, group.by = "annotations", split.by = "orig.ident")
```

```{r}
Idents(Myeloid_2) <- "orig.ident"
Pod1R <- subset(Myeloid_2, idents = "Pod1R")
Pod7R <- subset(Myeloid_2, idents = "Pod7R")
Pod14R <- subset(Myeloid_2, idents = "Pod14R")
```

```{r}
FeaturePlot(Pod1R, reduction = "umap", features = c("pseudotime"), split.by = "orig.ident", cols = viridis(10))
FeaturePlot(Pod7R, reduction = "umap", features = c("pseudotime"), split.by = "orig.ident", cols = viridis(10))
FeaturePlot(Pod14R, reduction = "umap", features = c("pseudotime"), split.by = "orig.ident", cols = viridis(10))
```

```{r}
FeaturePlot(Pod1R, reduction = "umap", features = c("entropy"), split.by = "orig.ident", cols = viridis(256))
FeaturePlot(Pod7R, reduction = "umap", features = c("entropy"), split.by = "orig.ident", cols = viridis(256))
FeaturePlot(Pod14R, reduction = "umap", features = c("entropy"), split.by = "orig.ident", cols = viridis(256))
```




























