```{r}
library(Seurat)
library(dplyr)
options(future.globals.maxSize = 8000 * 1024^2)
```

```{r}
load('../filtered_transplant_updated.Robj')
```

```{r}
sample <- ben_transplant_updated
```

```{r}
sample.list <- SplitObject(sample, split.by = "orig.ident")
sample.list <- sample.list[c("Pod14R","Pod1R","Pod7R")]
for (i in 1:length(sample.list)) {
    sample.list[[i]] <- SCTransform(sample.list[[i]], vars.to.regress = "percent.mt", verbose = FALSE, return.only.var.genes = TRUE)
}
```

```{r}
sample.features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 3000)
sample.list <- PrepSCTIntegration(object.list = sample.list, anchor.features = sample.features, 
    verbose = FALSE)

sample.anchors <- FindIntegrationAnchors(object.list = sample.list, normalization.method = "SCT", 
    anchor.features = sample.features, verbose = FALSE)
sample.integrated <- IntegrateData(anchorset = sample.anchors, normalization.method = "SCT", 
    verbose = FALSE)

sample.integrated <- RunPCA(sample.integrated, features = VariableFeatures(object = sample.integrated), npcs=50, verbose=TRUE)
sample.integrated <- FindNeighbors(sample.integrated, dims = 1:50, verbose = FALSE)
sample.integrated <- FindClusters(sample.integrated, resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0), verbose = FALSE)
sample.integrated <- RunUMAP(sample.integrated, dims = 1:50, verbose = FALSE)
```

```{r}
p1 <- DimPlot(sample.integrated, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(sample.integrated, reduction = "umap", group.by = "integrated_snn_res.0.3", repel = TRUE)
p1 + p2
```

```{r}
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "integrated_snn_res.0.3", repel = TRUE)
```
```{r}
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "RFP", repel = TRUE)
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "GFP", repel = TRUE)
DimPlot(sample.integrated, reduction = "umap", split.by = "orig.ident", group.by = "CCR2", repel = TRUE)
```

```{r}
saveRDS(sample.integrated, "./Integration/recipient_integrated.rds")
```

```{r}
DefaultAssay(sample.integrated) <- 'RNA'
sample.integrated <- NormalizeData(sample.integrated)
```

```{r}
DefaultAssay(sample.integrated) <- 'RNA'
Idents(sample.integrated) <- "integrated_snn_res.0.3"
sample.integrated.rnamarkers <- FindAllMarkers(sample.integrated, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.csv(sample.integrated.rnamarkers, file ="./Integration/res03_DE.csv", quote = FALSE)
```


